--Q1. What is the total revenue generated by male vs female customers ?

select gender,sum(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still used more than the average amount ?

select customer_id,purchase_amount
from customer
where discount_applied='Yes'
and purchase_amount >=(select avg(purchase_amount) from customer);

--Q3.Which are top 5 products with highest average review rating? 

select item_purchased,round(avg(review_rating):: numeric,2) as highest_review
from customer
group by item_purchased 
order by highest_review desc
limit 5

--Q4. Compare the average Purchase amount between standard and express shipping

select shipping_type,round(avg(purchase_amount),2) as avg_purchase
from customer
where shipping_type in ('Express','Standard')
group by shipping_type

--Q5. Do subscribed customers spend more?Compare average spend and total revenue
--between subscribers and non subscribers

select subscription_status,
count(customer_id) as total_customers,
round(sum(purchase_amount),2) as revenue,
round(avg(purchase_amount),2) as avg_amount
from customer
group by subscription_status
order by revenue,avg_amount desc

--Q6. Which 5 products have the highet percentage of purchases with discount applied?

SELECT item_purchased,
ROUND(
    (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)::numeric 
    / COUNT(*)) * 100, 2
) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into new ,returning,and loyal based on 
--there number of previous purchases,and show count of each segment

with cte as (select customer_id,previous_purchases,
case
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal' end as customers_segment
from customer
)
select customers_segment,count(*) as segment_count
from cte
group by customers_segment
order by segment_count desc

--Q8.What are the top 3 most purchased products within each category?

select * from (
select category,item_purchased,
count(*) as total_count,
row_number() over(partition by category order by count(*) desc) rn
from customer
group by category,item_purchased
) t
where rn<=3

--Q9. Are customers who are repeated (more than 5 previous purchased) are like to subscried?

select subscription_status,
count(*) as customers_count
from customer
where previous_purchases >5
group by subscription_status

--Q10. What is the revenue contribution of different age group
select * from customer

select age_grouped,sum(purchase_amount) as total_revenue
from customer
group by age_grouped
order by total_revenue desc





